---
driver:
  name: vagrant
  customize:
    natdnshostresolver1: "on"

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-10.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[mycookbook::default]
      - apt
      - yum
      - nginx
      - mysql::client
      - mysql::server
    attributes:
  - name: server
    run_list:
      - recipe[mycookbook::server]
      - apt
      - yum
      - runit
    attributes:
    excludes:
      - centos-6.4
